export const CHANGE_LANG = 'CHANGE_LANG';
export const PREV_SLIDE = 'PREV_SLIDE';
export const NEXT_SLIDE = 'NEXT_SLIDE';
export const INIT_SLIDES = 'INIT_SLIDES';
export const CHANGE_ANIMATING_STATE = 'CHANGE_ANIMATING_STATE';
